name: Egabrum
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48073
title: Academia de Ingles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3c277f'
    - '#e5422b'
    - '#000000'
    - '#b5b5b5'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
