name: Egabrum
favicon: null
layout_spectrum: 0.6476259948685765
typography_spectrum: 0.9227995439432561
title: Academia de Ingles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3c2381'
    - '#e74020'
    - '#b7b7b9'
    - '#6f6f6f'
  brandStrength: 0.75
  lightness: 0.3972774869762361
  saturation: 0.2715377495624125
  rhythmicContrast: 0.5
purpose: []
